version: '3'

services:

  streamer:
    build: .
    dockerfile: Dockerfile
    network_mode: "host"
    links:
     - ignite

  ignite:
    image: apacheignite/ignite
    environment:
       CONFIG_URI: https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-cache.xml
    volumes:
     - ./ignite:/var/lib/ignite:rw
    network_mode: "host"
  
  ignite-web-console:
    image: apacheignite/web-console-standalone
    volumes:
     - ./ignite-web-console:/var/lib/mongodb 
    ports:
     - "8080:80"
     - "3001:3001"