version: '2'

services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  PostgreSQL:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql