version: '3'
ser
services:
  web:
    build: .
    dockerfile: Dockerfile
    ports:
     - "5000"
    links:
     - elasticsearch
    volumes:
     - .:/code

  elasticsearch:
    image: elasticsearch
    network_mode: "host"
