version: '2'

services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - ".:/app"
    restart: always

  #PostgreSQL:
  #  image: postgres:latest
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - ./docker/postgresql:/var/lib/postgresql