FROM ubuntu:18.04

RUN apt-get update -y
RUN apt-get install -y python3-pip

WORKDIR app

COPY * /app/

RUN pip3 install -r requirements.txt

EXPOSE 5000

WORKDIR /app/

ENTRYPOINT ["python3"]
CMD ["runserver.py"]